### ISSUE TITLE
TCP injection in python not successful

### ISSUE THREAD

**Issue by Ayesha494** [thiagoralves/defcon26#2]
Hi Thiago,
I read your code here. I am trying to achieve somewhat same but in python language using Scapy tool for modbus packet crafting.
I am changing the payload bytes directly and injecting the packets.
However, my write Query packets are flagged as TCP spurious retransmissions in Wireshark and also they don't receive a response from the Factory I/O tool (my plant simulation). 
Could you please guide me how you are updating sequence numbers etc, in your code?
any help would be greatly appreciated as I am stuck in my code from quite some time now.
Regards.

**Comment by thiagoralves** [comment]
The injection code was written in C. It has nothing to do with Scapy and Python, neither is it a technique to replay packets. So no, what you are trying to do is not the same thing. The injection code written here crafts its own Modbus packets and sends that over a TCP socket several times per second.
